version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: spring_pg
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: